---
kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
  labels:
    app: traefik-ingress
spec:
  template:
    metadata:
      labels:
        app: traefik-ingress
        name: traefik-ingress
    spec:
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      hostNetwork: true
      containers:
        - image: traefik:1.4.6
          name: traefik-ingress
          ports:
          - name: http
            containerPort: 80
            hostPort: 80
          - name: admin
            containerPort: 8080
          securityContext:
            privileged: true
          args:
          - -d
          - --web
          - --kubernetes
