apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    environment: dev
    producer: lunchbadger
  name: gateway-lunchbadger-dev
data:
  gateway.conf: |-
    {{- if eq true .Values.production }}
    https: 
    port: ${EG_HTTPS_PORT:-8443}
    tls: 
      '*.lunchbadger.io': 
        key: /etc/lunchbadger-tls/lunchbadger.io.key.pem
        cert: /etc/lunchbadger-tls/lunchbadger.io.cert.pem
      api.lunchbadger.com: 
        key: /etc/lunchbadger-tls/lunchbadger.com.key.pem
        cert: /etc/lunchbadger-tls/lunchbadger.com.cert.pem
      kube-watcher.lunchbadger.com: 
        key: /etc/lunchbadger-tls/lunchbadger.com.key.pem
        cert: /etc/lunchbadger-tls/lunchbadger.com.cert.pem
      default: 
        key: /etc/lunchbadger-tls/lunchbadger.io.key.pem
        cert: /etc/lunchbadger-tls/lunchbadger.io.cert.pem
    {{- else }}
    http: 
      port: ${EG_HTTP_PORT:-8080}
    {{- end }}
    admin: # remove this section to disable admin API
      port: 9876
      hostname: localhost # use 0.0.0.0 to listen on all IPv4 interfaces
    policies:
      - proxy
      - jwt
      - cors
    serviceEndpoints:
      admin:
        url: http://localhost:9876
      traefik:
        url: http://{{ .Values.traefikAddress }}
      # configstore:
    apiEndpoints:
      schema:
        path: /schemas
      api:
        path: /
    {{- if eq true .Values.production }}
          
    {{- end }}
    pipelines: 
      schemas-api:
        apiEndpoints:
          - schema
        policies:
          - cors:
            - action:
                origin: ["http://localhost:8000", "https://app.lunchbadger.com", "dev.lunchbadger.com"]
                credentials: true
          - proxy:
              - action:
                  serviceEndpoint: admin
      lunchbadger-api:
        apiEndpoints:
          - api
        policies: 
          - cors:
            - action:
                origin: ["http://localhost:8000", "https://app.lunchbadger.com", {{ .Values.origin  | quote }}]
                credentials: true

    {{- if eq true .Values.production }}
          - jwt:
            - condition: ["not",
                ["oneOf",
                  ["allOf",
                    ["hostMatch", "*.lunchbadger.io"],
                    ["not", ["hostMatch", "internal-*.lunchbadger.io"]]
                  ],
                  ["allOf",
                    ["hostMatch", "api.lunchbadger.com"],
                    ["pathMatch", "^/git"]
                  ]
                ]
              ]
              action: 
                issuer: https://www.lunchbadger.com,
                audience: 4kzhU5LqlUpQJmjbMevWkWyt9adeKK,
                algorithms: ["RS256"]
                key: "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA7ATrA/pvXdzabRID6pBA\nA+i2zez6FG3SXw5peAV2oQUmd64JbO2vUMih4PIt5D/o6gHfzQDwI/5e8wpiNKKp\n81dpvy3uYecyfGT4x+FYQ4xj0p7dnczPlp5t1ottCXYQyyB07UZ4UsOT063CRhgi\n00HhlURBm+yjLwnlZv/VGDNzXNFX1+t+PbGC5Ab7R02Fsnp8TGfjUgzA6NDgerKi\nJcq/fSxRb5WSB/gscCGGWjvgIJrHOLI9ofaXFpoHCxePCsVkaR0JNz8Q89tIWvWv\n5msm062aD7y1ThfP6I3HeGf3dT6IavLOVD6Wk82/WN+aaQ7BKOstglWqzjJvcEvU\nOQIDAQAB\n-----END PUBLIC KEY-----"
    {{- end }}
          - proxy:
              - action:
                  serviceEndpoint: traefik
