apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    environment: dev
    producer: lunchbadger
  name: gateway-lunchbadger-dev
data:
  system.conf: |-
    db:
      redis:
        emulate: true
        host: localhost
        port: 6379
        namespace: EG

    cli:
      url: http://localhost:9876

    crypto:
      cipherKey: sensitiveKey
      algorithm: aes256
      saltRounds: 10
    session:
      secret: keyboard cat
      resave: false
      saveUninitialized: false
    accessTokens:
      timeToExpiry: 7200000
    refreshTokens:
      timeToExpiry: 7200000
    authorizationCodes:
      timeToExpiry: 300000

  gateway.conf: |-
    {{- if eq true .Values.production }}
    https:
      port: 443
      tls:
        "*.lunchbadger.io":
          key: "/etc/lunchbadger-tls/lunchbadger.io.key.pem",
          cert: "/etc/lunchbadger-tls/lunchbadger.io.cert.pem"
        "api.lunchbadger.com":
          key: "/etc/lunchbadger-tls/lunchbadger.com.key.pem",
          cert: "/etc/lunchbadger-tls/lunchbadger.com.cert.pem"
        "kube-watcher.lunchbadger.com":
          key: "/etc/lunchbadger-tls/lunchbadger.com.key.pem",
          cert: "/etc/lunchbadger-tls/lunchbadger.com.cert.pem"
        "default":
          key: "/etc/lunchbadger-tls/lunchbadger.io.key.pem",
          cert: "/etc/lunchbadger-tls/lunchbadger.io.cert.pem"
    {{- else }}
    http:
      port: 80
    {{- end }}
    admin:
      port: 9876
      hostname: localhost
    apiEndpoints:
      lunchbadger-api:
        path: '/'
    serviceEndpoints:
      backend:
        url: "http://traefik-ingress-service.kube-system"
    policies:
      - proxy
      - jwt
      - cors
      - rewrite
    pipelines:
      adminAPI:
        apiEndpoints:
          - api
        policies:
          - cors:
              origin:
                - http://localhost:8000
                - https://app.lunchbadger.com
                - {{ .Values.origin  | quote }}
              credentials: true
          - jwt:
              - action:
                  issuer: https://www.lunchbadger.com,
                  audience: 4kzhU5LqlUpQJmjbMevWkWyt9adeKK,
                  checkCredentialExistence: false
                  algorithms:
                    - RS256
                  key: {{ .Values.jwtPublicKey }}

          - proxy:
              - action:
                  serviceEndpoint: backend
