apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    environment: dev
    producer: lunchbadger
  name: gateway-lunchbadger-dev
data:
  system.conf: |-
    db:
      redis:
        emulate: ${EG_DB_EMULATE:-true}
        host: localhost
        port: 6379
        namespace: EG

    cli:
      url: http://localhost:9876

    crypto:
      cipherKey: sensitiveKey
      algorithm: aes256
      saltRounds: 10
    session:
      secret: keyboard cat
      resave: false
      saveUninitialized: false
    accessTokens:
      timeToExpiry: 7200000
    refreshTokens:
      timeToExpiry: 7200000
    authorizationCodes:
      timeToExpiry: 300000

  gateway.conf: |-
    {{- if eq true .Values.production }}
    http:
      port: 80
    {{- else }}
    https:
      port: 443
      tls:
        "*.lunchbadger.io":
          key: "/etc/lunchbadger-tls/lunchbadger.io.key.pem",
          cert: "/etc/lunchbadger-tls/lunchbadger.io.cert.pem"
        "api.lunchbadger.com":
          key: "/etc/lunchbadger-tls/lunchbadger.com.key.pem",
          cert: "/etc/lunchbadger-tls/lunchbadger.com.cert.pem"
        "kube-watcher.lunchbadger.com":
          key: "/etc/lunchbadger-tls/lunchbadger.com.key.pem",
          cert: "/etc/lunchbadger-tls/lunchbadger.com.cert.pem"
        "default":
          key: "/etc/lunchbadger-tls/lunchbadger.io.key.pem",
          cert: "/etc/lunchbadger-tls/lunchbadger.io.cert.pem"
    {{- end }}
    admin:
      port: 9876
      hostname: localhost
    apiEndpoints:
      lunchbadger-api:
        path: '/'
    serviceEndpoints:
      backend:
        url: "http://traefik-ingress-service"
    policies:
      - proxy
      - jwt
      - cors
      - rewrite
    pipelines:
      adminAPI:
        apiEndpoints:
          - api
        policies:
          - cors:
              origin:
                - http://localhost:8000
                - https://app.lunchbadger.com
                - {{ .Values.origin  | quote }}
              credentials: true
          - jwt:
              - action:
                  issuer: https://www.lunchbadger.com,
                  audience: 4kzhU5LqlUpQJmjbMevWkWyt9adeKK,
                  checkCredentialExistence: false
                  algorithms:
                    - RS256
                  key: -----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA7ATrA/pvXdzabRID6pBA\nA+i2zez6FG3SXw5peAV2oQUmd64JbO2vUMih4PIt5D/o6gHfzQDwI/5e8wpiNKKp\n81dpvy3uYecyfGT4x+FYQ4xj0p7dnczPlp5t1ottCXYQyyB07UZ4UsOT063CRhgi\n00HhlURBm+yjLwnlZv/VGDNzXNFX1+t+PbGC5Ab7R02Fsnp8TGfjUgzA6NDgerKi\nJcq/fSxRb5WSB/gscCGGWjvgIJrHOLI9ofaXFpoHCxePCsVkaR0JNz8Q89tIWvWv\n5msm062aD7y1ThfP6I3HeGf3dT6IavLOVD6Wk82/WN+aaQ7BKOstglWqzjJvcEvU\nOQIDAQAB\n-----END PUBLIC KEY-----

          - proxy:
              - action:
                  serviceEndpoint: backend
