{{- if eq false .Values.production -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    environment: dev
    producer: lunchbadger
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80 
      protocol: TCP
  selector:
    app: {{ .Chart.Name }}
    environment: dev
    producer: lunchbadger
  type: LoadBalancer
{{- end }}
