apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    environment: dev
    producer: lunchbadger
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
spec:
  ports:
    - name: http
      port: 443
      targetPort: 443
      protocol: TCP
  selector:
    app: {{ .Chart.Name }}
    environment: dev
    producer: lunchbadger
  type: LoadBalancer
