apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    environment: dev
    producer: lunchbadger
spec:
  ports:
{{- if eq true .Values.production }}
    - port: 443
      targetPort: 8443 
      protocol: TCP
{{- else }}
    - port: 80
      targetPort: 8080 
      protocol: TCP
{{- end }}
  selector:
    app: {{ .Chart.Name }}
    environment: dev
    producer: lunchbadger
  type: LoadBalancer
