dependencies:
  - name: traefik
    version: 1.0.0-beta
    condition: traefik.enabled
  - name: configstore 
    version: 1.0.0-beta
    condition: configstore.enabled
  - name: actualizer
    version: 1.0.0-beta
    condition: actualizer.enabled
  - name: gateway 
    version: 1.0.0-beta
    condition: gateway.enabled
  - name: redis
    version: 1.1.7
    condition: redis.enabled
  - name: prometheus
    version: 4.6.17
    condition: prometheus.enabled
  - name: grafana
    version: 0.5.5
    condition: grafana.enabled
