dependencies:
  - name: traefik
    repository: file://./traefik
    version: 1.0.0
    condition: traefik.enabled
  - name: configstore
    repository: file://./configstore
    version: 1.2.0
    condition: configstore.enabled
  - name: actualizer
    repository: file://./actualizer
    version: 1.2.0
    condition: actualizer.enabled
  - name: gitea
    version: 1.6.0
    repository: https://jfelten.github.io/helm-charts/charts
    condition: gitea.enabled
  - name: git-api
    repository: file://./git-api
    version: 1.2.0
    condition: git-api.enabled
  - name: kubeless
    repository: file://./kubeless
    version: 1.2.0
    condition: kubeless.enabled
  - name: gateway 
    repository: file://./gateway
    version: 1.2.0
    condition: gateway.enabled
  - name: kube-watcher 
    repository: file://./kube-watcher
    version: 1.2.0
    condition: kube-watcher.enabled
  - name: redis
    repository: "@stable"
    version: 4.2.7
    condition: redis.enabled
  - name: prometheus
    repository: "@stable"
    version: 7.4.0
    condition: prometheus.enabled
  - name: grafana
    repository: "@stable"
    version: 1.17.3
    condition: grafana.enabled
  - name: kubernetes-dashboard
    repository: "@stable"
    version: 0.8.0
    condition: kubernetes-dashboard.enabled
