traefik:
  enabled: true
redis:
  enabled: true
prometheus:
  enabled: false
grafana:
  enabled: false
kubernetes-dashboard:
  enabled: false
configstore:
  enabled: true
actualizer:
  enabled: true
kube-watcher:
  enabled: true
gateway:
  enabled: true
storageClass:
  enabled: false
  name: standard
  type: gp2
  zones: 'us-west-2a, us-west-2b, us-west-2c'
  iopsPerGB: 10
