apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    environment: dev
    producer: lunchbadger
  name: gateway-lunchbadger-dev
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: gateway
      environment: dev
      producer: lunchbadger
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gateway
        environment: dev
        producer: lunchbadger
    spec:
      containers:
      - env:
        - name: DEBUG
          value: gateway:*
        image: 410240865662.dkr.ecr.us-west-2.amazonaws.com/gateway:0.0.4
        imagePullPolicy: Always
        name: gateway
        ports:
        - containerPort: 443
          hostPort: 443
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /etc/lunchbadger
          name: config
          readOnly: true
        - mountPath: /etc/lunchbadger-tls
          name: lunchbadger-tls
          readOnly: true
      dnsPolicy: ClusterFirst
      hostNetwork: true
      nodeSelector:
        lunchbadger.com/node-type: public
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: gateway-lunchbadger-dev
        name: config
      - name: lunchbadger-tls
        secret:
          defaultMode: 420
          secretName: lunchbadger-tls