apiVersion: v1
kind: Service
metadata:
  name: graphql-service
  namespace: {{ .Values.namespace }}
  selfLink: api/v1/namespaces/{{ .Values.namespace }}/services/graphql-service
  uid: 7abd6e31-2bb9-11e9-aef6-0ac4997a9b84
  resourceVersion: 377882110
  creationTimestamp: 2019-02-08T15:52:03Z
  # annotations:
    # kubectl.kubernetes.io/last-applied-configuration: {\"apiVersion\":\"v1\",\"kind\":\"Service\",\"metadata\":{\"annotations\":{},\"name\":\"graphql-service\",\"namespace\":\"default\"},\"spec\":{\"ports\":[{\"port\":80,\"protocol\":\"TCP\",\"targetPort\":8080}],\"selector\":{\"app\":\"soapdemo\"}}}\n
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.containerPort }}
      protocol: {{ .Values.service.protocol }}
  selector:
    app: {{ .Chart.Name }}
  clusterIP: {{ .Values.service.clusterIP }}
  type: {{ .Values.service.type }}
  sessionAffinity: None
status:
  loadBalancer: {}
