apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    environment: dev
    producer: lunchbadger
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
spec:
  ports:
    {{- if eq true .Values.production }}
    - name: http
      port: 443
      targetPort: 443
      protocol: TCP
    {{- else }}
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    {{- end }}
  selector:
    app: {{ .Chart.Name }}
    environment: dev
    producer: lunchbadger
  type: LoadBalancer
  {{- if .Values.externalIPs }}
  externalIPs:
  {{- range.Values.externalIPs }}
  - {{ . }}
  {{- end }}
  {{- end }}
