{{- if .Values.rbac.enabled }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: actualizer-kubectl-proxy
rules:
  - apiGroups:
      - ""
    resources:
      - ingresses
      - deployments
      - services
      - configmaps
      - pods
    verbs:
      - get
      - list
      - create
      - update
      - patch
      - delete
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - extensions
      - apps
    resources:
      - deployments
      - configmaps
    verbs:
      - get
      - list
      - create
      - update
      - patch
      - delete
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: actualizer-kubectl-proxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: actualizer-kubectl-proxy
subjects:
- kind: ServiceAccount
  name: actualizer-kubectl-proxy
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: actualizer-kubectl-proxy
  namespace: default
{{ if .Values.rbac.pullSecret }}
imagePullSecrets:
  - name: {{ .Values.rbac.pullSecret | }}
{{ end }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: sls-api-role
rules:
  - apiGroups: 
      - "kubeless.io"
    resources: 
      - "functions"
    verbs: ["create", "get", "delete", "list", "update", "patch"]
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - configmaps
      - pods/log
    verbs:
      - get
      - list
      - watch
  -
    apiGroups: 
      - "autoscaling"
    resources: 
      - "horizontalpodautoscalers"
    verbs: ["create", "get", "delete", "list", "update", "patch"]
  - apiGroups:
    - extensions
    resources:
    - ingresses
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: sls-api-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sls-api-role
subjects:
- kind: ServiceAccount
  name: sls-api
  namespace: customer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sls-api
  namespace: customer
  {{ if .Values.rbac.pullSecret }}
imagePullSecrets:
  - name: {{ .Values.rbac.pullSecret | }}
  {{ end }}
{{- end }}
