{{- if .Values.rbac.enabled }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: actualizer-kubectl-proxy
rules:
  - apiGroups:
      - ""
    resources:
      - ingresses
      - deployments
      - services
      - configmaps
      - pods
    verbs:
      - get
      - list
      - create
      - update
      - patch
      - delete
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - extensions
      - apps
    resources:
      - deployments
      - configmaps
    verbs:
      - get
      - list
      - create
      - update
      - patch
      - delete
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: actualizer-kubectl-proxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: actualizer-kubectl-proxy
subjects:
- kind: ServiceAccount
  name: actualizer-kubectl-proxy
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: actualizer-kubectl-proxy
  namespace: default
{{- end }}
