rbac:
  enabled: true
ingressHost: kube-watcher.dev-api.lunchbadger.com
images:
  kubeWatcher:
    repository: 410240865662.dkr.ecr.us-west-2.amazonaws.com/kube-watcher
    tag: v2.0.2
    pullPolicy: Always
  kubectl:
    repository: 410240865662.dkr.ecr.us-west-2.amazonaws.com/kubectl
    tag: 1.4.6
    pullPolicy: Always
