actualizer:
  enabled: true
  adminOrigin: ""
  customerDomain: cluster.local
  gitAPIURL: http://git-api.default
  images:
    actualizer:
      tag: 0.2.0
    kubectl:
      tag: 1.4.6
  rbac:
    enabled: true
    pullSecret: awsecr-cred
  serverlessAPIURLTemplate: http://sls-api-$PRODUCER-$ENV.customer
  versions:
    gateway: master
    serverless: validation
    workspace: "0.1.464"
  workspaceAPIURLTemplate: http://workspace-$PRODUCER-$ENV.customer:81/api
configstore:
  enabled: true
  image:
    tag: external_push
  ingressHost: api.cluster.local

gitea:
  enabled: true
  persistence:
    enabled: true
    giteaSize: 40Gi
    postgresSize: 5Gi
    storageClass: standard
    accessMode: ReadWriteOnce
    annotations:
      "helm.sh/resource-policy": keep
kubeless:
  enabled: true

gateway:
  enabled: false
  global: {}
  image:
    pullPolicy: Always
    repository: expressgateway/express-gateway
    tag: v1.9.1
  jwtPublicKey: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA7ATrA/pvXdzabRID6pBA
    A+i2zez6FG3SXw5peAV2oQUmd64JbO2vUMih4PIt5D/o6gHfzQDwI/5e8wpiNKKp
    81dpvy3uYecyfGT4x+FYQ4xj0p7dnczPlp5t1ottCXYQyyB07UZ4UsOT063CRhgi
    00HhlURBm+yjLwnlZv/VGDNzXNFX1+t+PbGC5Ab7R02Fsnp8TGfjUgzA6NDgerKi
    Jcq/fSxRb5WSB/gscCGGWjvgIJrHOLI9ofaXFpoHCxePCsVkaR0JNz8Q89tIWvWv
    5msm062aD7y1ThfP6I3HeGf3dT6IavLOVD6Wk82/WN+aaQ7BKOstglWqzjJvcEvU
    OQIDAQAB
    -----END PUBLIC KEY-----
  origin: http://staging.lunchbadger.com
  producersAPIKey: {}
  production: false
  ingressAddress: http://10.3.18.145
  useNodeSelector: false
grafana:
  enabled: false
kube-watcher:
  enabled: false
  images:
    kubeWatcher:
      pullPolicy: Always
      repository: 410240865662.dkr.ecr.us-west-2.amazonaws.com/kube-watcher
      tag: v2.0.2
    kubectl:
      pullPolicy: Always
      repository: 410240865662.dkr.ecr.us-west-2.amazonaws.com/kubectl
      tag: 1.4.6
  ingressHost: kube-watcher.cluster.local
  rbac:
    enabled: true
kubernetes-dashboard:
  enabled: false
prometheus:
  enabled: false

# check values here: https://github.com/helm/charts/tree/master/stable/redis
redis:
  enabled: true
  master:
    persistence:
      storageClass: standard

storageClass:
  enabled: false

storageClassCeph:
  enabled: true
  name: standard

traefik:
  enabled: false

git-api:
  enabled: false