apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      run: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        run: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: GIT_API_URL
              value: {{ .Release.Name }}-git-api.default
            - name: DEBUG
              value: {{ .Values.debugPattern }}
          ports:
            - containerPort: 3002
          resources:
            requests:
              memory: "128Mi"
            limits:
              memory: "128Mi"
