apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      run: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        run: {{ .Chart.Name }}
    spec:
      {{- if eq true .Values.useNodeSelector }}
      nodeSelector:
        lunchbadger.com/node-type: public
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: GIT_API_URL
              value: {{ .Values.gitAPIURL }}
            - name: DEBUG
              value: {{ .Values.debugPattern }}
          ports:
            - containerPort: 3002
          volumeMounts:
            - mountPath: {{ .Values.persistence.mountPath }}
              name: data
          resources:
            requests:
              memory: "768Mi"
            limits:
              memory: "768Mi"
      volumes:
        - name: data
          emptyDir: {}
{{- end -}}
