apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    run: {{ .Chart.Name }}
spec:
  ports:
    - port: 80
      targetPort: 3002
      protocol: TCP
  selector:
    run: {{ .Chart.Name }}
  type: ClusterIP
