actualizer:
  enabled: true
  adminOrigin: ""
  customerDomain: staging.lunchbadger.io
  images:
    actualizer:
      tag: 0.2.20
  rbac:
    enabled: true
  serverlessAPIURLTemplate: http://sls-api-$PRODUCER-$ENV.customer
  versions:
    gateway: master
    serverless: validation
    workspace: "0.2.4"
  workspaceAPIURLTemplate: http://workspace-$PRODUCER-$ENV.customer:81/api
configstore:
  enabled: true
  image:
    tag: external_push
  ingressHost: api.staging.lunchbadger.io

# custom config need to be mounted in order to skip web install screen

# create admin user:
# gitea admin create-user --name=test --password=test --email=test@xx.com --admin

# generate token
# curl -X POST "http://localhost:3000/api/v1/users/test/tokens" -H "accept: application/x-www-form-urlencoded" -H "authorization: Basic dGVzdDp0ZXN0" -F name=ttxxx

# response sha1 is the access key
# {"id":7,"name":"ttxxx","sha1":"2283d9f73439c7b34a644197875e1bf84923a960"}
gitea:
  enabled: true
  persistence:
    enabled: true
    giteaSize: 40Gi
    postgresSize: 5Gi
    storageClass: zonec
    accessMode: ReadWriteOnce
  config:
    disableInstaller: true
        
    ## automatically creates admin user
    ## requires config.disableInstaller:true and valid config.secretKey
  adminUser:
    enabled: false
    username: lunchbadger
    passwrord: lunchbadger
    email: lunchbadger@lunchbadger.com
kubeless:
  enabled: false

gateway:
  enabled: false
  global: {}
  image:
    pullPolicy: Always
    repository: expressgateway/express-gateway
    tag: v1.9.1
  jwtPublicKey: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA7ATrA/pvXdzabRID6pBA
    A+i2zez6FG3SXw5peAV2oQUmd64JbO2vUMih4PIt5D/o6gHfzQDwI/5e8wpiNKKp
    81dpvy3uYecyfGT4x+FYQ4xj0p7dnczPlp5t1ottCXYQyyB07UZ4UsOT063CRhgi
    00HhlURBm+yjLwnlZv/VGDNzXNFX1+t+PbGC5Ab7R02Fsnp8TGfjUgzA6NDgerKi
    Jcq/fSxRb5WSB/gscCGGWjvgIJrHOLI9ofaXFpoHCxePCsVkaR0JNz8Q89tIWvWv
    5msm062aD7y1ThfP6I3HeGf3dT6IavLOVD6Wk82/WN+aaQ7BKOstglWqzjJvcEvU
    OQIDAQAB
    -----END PUBLIC KEY-----
  origin: http://staging.lunchbadger.com
  producersAPIKey: {}
  production: false
  ingressAddress: http://10.3.18.145
grafana:
  enabled: false
kube-watcher:
  enabled: true
  images:
    kubeWatcher:
      pullPolicy: Always
      repository: 410240865662.dkr.ecr.us-west-2.amazonaws.com/kube-watcher
      tag: state_fix
  ingressHost: kube-watcher.staging.lunchbadger.io
  rbac:
    enabled: true
kubernetes-dashboard:
  enabled: false
prometheus:
  enabled: false

# check values here: https://github.com/helm/charts/tree/master/stable/redis
redis:
  enabled: true
  master:
    persistence:
      storageClass: standard

storageClass:
  enabled: true

storageClass2:
  enabled: true


#storageClassCeph:
#  enabled: true
#  name: standard

traefik:
  enabled: false

git-api:
  enabled: true
  giteaSecret: 9ed8c58701197315d0a14ce4d961b1f9f13dfc5a
