{{- if .Values.mainIngress.enabled -}}
# this should contain all routes to internal services
# another variant is to move it to EG
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
spec:
  rules:
  - host: {{ .Values.mainIngress.ingressHost }}
    http:
      paths:
      - backend:
          serviceName: {{ .Release.Name }}-git-api
          servicePort: 80
        path: /users
      - backend:
          serviceName: kube-watcher
          servicePort: 80
        path: /v2
      - backend:
          serviceName: configstore
          servicePort: 80
{{- end -}}
