{{- if .Values.storageClassCeph.enabled -}}
# TODO: allow params override

apiVersion: v1
data:
  key: QVFDb205bGJJS21zTWhBQVlteTR5RGJGbXI4dllKN21YTXlDemc9PQ==
kind: Secret
metadata:
  name: ceph-secret-user
  namespace: default
type: kubernetes.io/rbd
---
apiVersion: v1
data:
  key: QVFDb205bGJJS21zTWhBQVlteTR5RGJGbXI4dllKN21YTXlDemc9PQ==
kind: Secret
metadata:
  name: ceph-secret
  namespace: kube-system
type: kubernetes.io/rbd
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{.Values.storageClassCeph.name | quote}}
provisioner: kubernetes.io/rbd
parameters:
  monitors: 10.0.0.203:6789,10.0.0.204:6789,10.0.0.205:6789
  adminId: admin
  adminSecretName: ceph-secret
  adminSecretNamespace: kube-system
  pool: rbd
  userId: admin
  userSecretName: ceph-secret-user
  userSecretNamespace: default
  fsType: ext4
  imageFormat: "2"
  imageFeatures: "layering"
{{- end -}}